"""Solve script generation — template registry + priority routing.
The counterpart of intelpwn's exploit generator.

Two hard rules (inherited from intelpwn: "never emit a script that is bound to crash"):
  1. A generated script uses **only the standard library at its core**, so
     `python3 solve_xxx.py` just runs; when long code such as LLL/Coppersmith is
     needed, the script explicitly imports this repo's utilities and states the
     preconditions in a comment.
  2. When there is no working route, be honest and emit a `[skeleton]`: write down
     the attack idea, the oracle it needs and where the gap is — never pretend it works.
"""

import os

from ..utils import encoding as _E

_SOLVERS = []
_BUILTINS_LOADED = False


def register_solver(name, predicate, gen_fn, priority=500, meta=None):
    """Register a solve template

    predicate(results) -> bool          applicability test
    gen_fn(results, params) -> str      returns the complete script
    priority: lower runs first (built-ins 10-90, plugins default 500, skeleton 999)
    """
    if not callable(predicate) or not callable(gen_fn):
        raise ValueError("predicate/gen_fn must be callables")
    _SOLVERS.append({"name": name, "predicate": predicate, "gen": gen_fn,
                     "priority": priority, "meta": meta or {}})
    _SOLVERS.sort(key=lambda s: s["priority"])


def list_solvers():
    return [(s["name"], s["priority"]) for s in _SOLVERS]


# ────────────────────────── shared fragments ──────────────────────────

_HEAD = ("#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n"
         "# Generated by cryptoexp -- dependency-free, run with python3\n")

# Inline Vigenere search, only used when `import cryptoexp` fails inside the generated
# script. It is the historical weak version (IoC + per-column chi-square, no whole-text
# refinement): it is kept as a last resort, not as the recommended path.
_VIGENERE_FALLBACK_BODY = '''
def ioc(s):
    ls = [c.lower() for c in s if c.isalpha()]
    n = len(ls)
    if n < 2:
        return 0.0
    return sum(ls.count(c) * (ls.count(c) - 1) for c in set(ls)) / (n * (n - 1))


FREQ = {'e': 12.7, 't': 9.06, 'a': 8.17, 'o': 7.51, 'i': 6.97, 'n': 6.75, 's': 6.33,
        'h': 6.09, 'r': 5.99, 'd': 4.25, 'l': 4.03, 'c': 2.78, 'u': 2.76, 'm': 2.41,
        'w': 2.36, 'f': 2.23, 'g': 2.02, 'y': 1.97, 'p': 1.93, 'b': 1.29, 'v': 0.98}

letters = [c for c in ct if c.isalpha()]
best_kl = max(range(1, min(20, len(letters) // 3) + 1),
              key=lambda kl: sum(ioc(''.join(letters[i::kl])) for i in range(kl)) / kl)
shifts = []
for i in range(best_kl):
    col = ''.join(letters[i::best_kl]).lower()

    def chi(s):
        shifted = ''.join(chr((ord(c) - 97 - s) % 26 + 97) for c in col)
        return sum((shifted.count(c) / len(shifted) * 100 - p) ** 2 / p
                   for c, p in FREQ.items())

    shifts.append(min(range(26), key=chi))
key = ''.join(chr(s + 97) for s in shifts)
pt = ''.join(chr((ord(c.lower()) - 97 - shifts[i % best_kl]) % 26 +
                 (65 if c.isupper() else 97)) if c.isalpha() else c
             for i, c in enumerate(ct))
print("[+] inline fallback key =", key)
print("[+] inline fallback plaintext =", pt)
'''

_IROOT_FN = '''
def iroot(n, k):
    """Integer k-th root (Newton iteration), returns (root, exact)"""
    if n < 0:
        raise ValueError("negative")
    if n in (0, 1) or k == 1:
        return n, True
    x = 1 << ((n.bit_length() + k - 1) // k)
    while True:
        y = ((k - 1) * x + n // (x ** (k - 1))) // k
        if y >= x:
            break
        x = y
    while x ** k > n:
        x -= 1
    while (x + 1) ** k <= n:
        x += 1
    return x, x ** k == n
'''

_INT_TO_BYTES = '''
def itob(x):
    return x.to_bytes((x.bit_length() + 7) // 8, 'big') if x else b''
'''


def _reporoot() -> str:
    """Directory to put on sys.path so `import cryptoexp` works inside a script

    src layout: this file is `<root>/src/cryptoexp/core/solve.py`, so the importable
    root is the parent of the *package* directory (`.../src`). It used to return the
    package directory itself, and every generated script that imported the library
    died with ModuleNotFoundError: No module named 'cryptoexp'.
    """
    package_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.path.dirname(package_dir)


def _params(results):
    """Parameter extraction always goes through the analysis layer's collect_params
    (one implementation, so analysis and generation cannot drift apart)"""
    from .analysis.rsa import collect_params
    ctx = results.get("_ctx") or {}
    rsa = (results.get("rsa") or {}).get("params") or {}
    raw = collect_params(ctx)
    p = {}
    p["n"] = raw.get("n")
    p["e"] = raw.get("e")
    p["c"] = raw.get("c")
    p["n_list"] = raw.get("n_list") or []
    p["c_list"] = raw.get("c_list") or []
    for key in ("p", "q", "dp", "d", "phi"):
        if raw.get(key):
            p[key] = raw[key]
    p["params_meta"] = rsa
    blobs = (results.get("encoding") or {}).get("blobs") or []
    p["blobs"] = blobs
    p["candidates"] = {
        "encoding": (results.get("encoding") or {}).get("candidates", []),
        "classical": (results.get("classical") or {}).get("candidates", []),
    }
    p["lcg"] = (results.get("numbertheory") or {}).get("lcg")
    p["knapsack"] = (results.get("lattice") or {}).get("knapsack")
    p["coppersmith"] = (results.get("lattice") or {}).get("coppersmith")
    p["symmetric"] = results.get("symmetric") or {}
    p["crc"] = results.get("crc") or {}
    p["lfsr"] = results.get("lfsr") or {}
    crc_params = (p["crc"].get("params") or {})
    p["crc_prefix"] = crc_params.get("prefix", b"")
    p["crc_suffix"] = crc_params.get("suffix", b"")
    p["crc_target"] = crc_params.get("target", 0)
    p["crc_unknown_len"] = crc_params.get("unknown_len", 0)
    p["raw_text"] = ctx.get("raw_text", "")
    return p


def _bubble_comment(text: str) -> str:
    return "\n".join(f"# {line}" if line.strip() else "#" for line in text.splitlines())


def _blob_text(blob: dict) -> str:
    """Ciphertext for generated scripts: never the display-truncated variant"""
    return blob.get("full_text") or blob.get("text", "")


def _hex_ciphertext(blob: dict) -> bool:
    """XOR templates require real hex ciphertext.

    A Caesar/Vigenere text is not hex, and routing it to an XOR template produced a
    script that crashed in bytes.fromhex() (caught by the generated-script test).
    """
    text = _blob_text(blob)
    return _E.from_hex(text) is not None and len(text.strip()) >= 8


# ────────────────────────── RSA templates ──────────────────────────

def gen_rsa_direct(results, params):
    n, e, c = params["n"], params["e"], params["c"]
    lines = [_HEAD, "# === RSA: private key material known -> decrypt directly ===", _INT_TO_BYTES]
    if params.get("p") and params.get("q"):
        lines.append(f"n = {n}\ne = {e}\nc = {c}\np = {params['p']}\nq = {params['q']}")
        body = '''
phi = (p - 1) * (q - 1)
d = pow(e, -1, phi)
m = pow(c, d, n)
print("[+] flag:", itob(m))
'''
    elif params.get("d"):
        lines.append(f"n = {n}\ne = {e}\nc = {c}\nd = {params['d']}")
        body = '''
m = pow(c, d, n)
print("[+] flag:", itob(m))
'''
    else:
        phi_in = params.get("phi") or params.get("phi_n")
        lines.append(f"n = {n}\ne = {e}\nc = {c}\nphi = {phi_in}")
        body = '''
import math

# recover p and q from phi: p+q = n - phi + 1, solve the quadratic
s = n - phi + 1
disc = s * s - 4 * n
r = math.isqrt(disc)          # integer sqrt: disc**0.5 overflows on real keys
assert r * r == disc, "wrong phi: discriminant is not a perfect square"
p = (s + r) // 2
q = (s - r) // 2
assert p * q == n, "factorization check failed"
d = pow(e, -1, (p - 1) * (q - 1))
print("[+] flag:", itob(pow(c, d, n)))
'''
    lines.append(body)
    return "\n".join(lines)


def gen_rsa_small_e(results, params):
    n, e, c = params["n"], params["e"], params["c"]
    return "\n".join([_HEAD, "# === RSA: small public exponent (m^e < n) -> integer root ===",
                      _IROOT_FN, _INT_TO_BYTES,
                      f"n = {n}\ne = {e}\nc = {c}",
                      '''
root, exact = iroot(c, e)
assert exact, "c is not a perfect e-th power -- use the broadcast template"
m = root
assert pow(m, e) == c, "root check failed"
print("[+] flag:", itob(m))
'''])


def gen_rsa_shared_prime(results, params):
    ns = [v for v in dict.fromkeys(params["n_list"] or [params["n"]]) if v]
    cs = params["c_list"]
    e = params["e"]
    return "\n".join([_HEAD, "# === RSA: shared factor across moduli -> gcd factorization ===", _INT_TO_BYTES,
                      "import math",
                      f"ns = {ns}\ncs = {cs}\ne = {e}",
                      '''
for i in range(len(ns)):
    for j in range(i + 1, len(ns)):
        g = math.gcd(ns[i], ns[j])
        if 1 < g < min(ns[i], ns[j]):
            for n in (ns[i], ns[j]):
                p = math.gcd(n, g)
                if 1 < p < n:
                    q = n // p
                    phi = (p - 1) * (q - 1)
                    d = pow(e, -1, phi)
                    for c in cs:
                        if c < n:
                            m = pow(c, d, n)
                            print("[+] flag:", itob(m))
'''])


def gen_rsa_broadcast(results, params):
    e = params["e"]
    ns = [v for v in dict.fromkeys(params["n_list"]) if v]
    cs = params["c_list"]
    return "\n".join([_HEAD, "# === RSA: low-exponent broadcast (Håstad) -> CRT + root ===", _IROOT_FN,
                      _INT_TO_BYTES, "from math import gcd",
                      f"e = {e}\nns = {ns[:e] if e else ns}\ncs = {cs[:e] if e else cs}",
                      '''
def crt(pairs):
    x, M = 0, 1
    for a, m in pairs:
        g = gcd(M, m)
        assert g == 1, "moduli are not coprime, use the shared-factor template"
        inv = pow(M % m, -1, m)
        t = ((a - x) % m) * inv % m
        x, M = (x + M * t) % (M * m), M * m
    return x % M, M

C, M = crt(list(zip(cs, ns)))
root, exact = iroot(C, e)
assert exact, "still not a perfect e-th power after CRT (plaintext may be padded)"
print("[+] flag:", itob(root))
'''])


def gen_rsa_wiener(results, params):
    n, e, c = params["n"], params["e"], params["c"]
    return "\n".join([_HEAD, "# === RSA: Wiener attack (d too small) -> continued fraction convergents ===",
                      _INT_TO_BYTES, "import math",
                      f"n = {n}\ne = {e}\nc = {c}",
                      '''
def cf(a, b):
    out = []
    while b:
        out.append(a // b)
        a, b = b, a % b
    return out

def convergents(seq):
    h0, h1, k0, k1 = 1, seq[0], 0, 1
    yield h1, k1
    for a in seq[1:]:
        h0, h1 = h1, a * h1 + h0
        k0, k1 = k1, a * k1 + k0
        yield h1, k1

for k, d in convergents(cf(e, n)):
    if k == 0:
        continue
    if (e * d - 1) % k:
        continue
    phi = (e * d - 1) // k
    s = n - phi + 1
    disc = s * s - 4 * n
    if disc < 0:
        continue
    r = math.isqrt(disc)          # integer sqrt: disc**0.5 overflows on real keys
    if r * r != disc or (s + r) % 2:
        continue
    p, q = (s + r) // 2, (s - r) // 2
    if p * q == n:
        print("[+] Wiener recovered d =", d)
        print("[+] flag:", itob(pow(c, d, n)))
        break
'''])


def gen_rsa_fermat(results, params):
    n, e, c = params["n"], params["e"], params["c"]
    return "\n".join([_HEAD, "# === RSA: Fermat factorization (p and q close) ===", _INT_TO_BYTES,
                      f"n = {n}\ne = {e}\nc = {c}",
                      '''
import math

a = math.isqrt(n)             # integer sqrt: n**0.5 overflows on real keys
if a * a < n:
    a += 1
for _ in range(2000000):
    b2 = a * a - n
    b = math.isqrt(b2)
    if b * b == b2:
        p, q = a - b, a + b
        assert p * q == n
        d = pow(e, -1, (p - 1) * (q - 1))
        print("[+] flag:", itob(pow(c, d, n)))
        break
    a += 1
else:
    print("[-] no factorization within 2,000,000 rounds (p and q are not close enough)")
'''])


def gen_rsa_factor(results, params):
    n, e, c = params["n"], params["e"], params["c"]
    return "\n".join([_HEAD, "# === RSA: direct factorization (Pollard rho) -- for modest n bit sizes ===",
                      _INT_TO_BYTES, "import math, random",
                      f"n = {n}\ne = {e}\nc = {c}",
                      '''
def rho(n):
    if n % 2 == 0:
        return 2
    while True:
        x = y = random.randrange(2, n)
        cst = random.randrange(1, n)
        d = 1
        while d == 1:
            x = (x * x + cst) % n
            y = (y * y + cst) % n
            y = (y * y + cst) % n
            d = math.gcd(abs(x - y), n)
        if d != n:
            return d

p = rho(n)
q = n // p
assert p * q == n
d = pow(e, -1, (p - 1) * (q - 1))
print("[+] p =", p)
print("[+] flag:", itob(pow(c, d, n)))
'''])


def gen_rsa_dp_leak(results, params):
    n, e, c, dp = params["n"], params["e"], params["c"], params["dp"]
    return "\n".join([_HEAD, "# === RSA: dp leak -> gcd(2^(e*dp) - 2, n) factorization ===",
                      _INT_TO_BYTES, "import math",
                      f"n = {n}\ne = {e}\nc = {c}\ndp = {dp}",
                      '''
p = math.gcd(pow(2, e * dp, n) - 2, n)
assert 1 < p < n, "gcd gave no factor (wrong dp or e)"
q = n // p
d = pow(e, -1, (p - 1) * (q - 1))
print("[+] flag:", itob(pow(c, d, n)))
'''])


def gen_rsa_coppersmith(results, params):
    n, e, c = params["n"], params["e"], params["c"]
    latt = (results.get("lattice") or {}).get("coppersmith") or {}
    p_found = latt.get("p")
    root = _reporoot()
    if p_found:
        return "\n".join([_HEAD,
                          "# === RSA: Coppersmith known high bits of p (solved; replay decryption) ===",
                          _INT_TO_BYTES,
                          f"n = {n}\ne = {e}\nc = {c}\np = {int(p_found, 16)}",
                          '''
q = n // p
d = pow(e, -1, (p - 1) * (q - 1))
print("[+] flag:", itob(pow(c, d, n)))
'''])
    return "\n".join([
        _HEAD,
        "# === RSA: Coppersmith known high bits of p — [skeleton] ===",
        _bubble_comment("small root missed; more known bits or larger lattice parameters m/t are needed."),
        f'import sys; sys.path.insert(0, r"{root}")',
        "from cryptoexp.utils.lattice import known_high_bits_factor",
        f"n = {n}",
        "# p_high = 0x...      # <- fill in the high bits of p given by the challenge",
        "# known_bits = 200    # <- fill in the number of known bits",
        "raise SystemExit('fill in p_high / known_bits and rerun')",
    ])


# ────────────────────────── encoding / classical ──────────────────────────

def gen_xor_single(results, params):
    blob = next((b for b in params["blobs"] if b.get("xor")), None)
    text = _blob_text(blob) if blob else ""
    hint = b""
    if blob and blob["xor"]:
        hint = bytes([blob["xor"][0]["top"][0]["key"]])
    return "\n".join([_HEAD, "# === single-byte XOR brute force ===", "import re",
                      f"ct_hex = {text!r}",
                      "# key recovered during analysis, inlined like an exploit address",
                      f"HINT_KEY = {hint!r}",
                      '''
ct = bytes.fromhex(re.sub(r'\\s', '', ct_hex))
WORDS = (b'flag', b'ctf', b'the', b'and', b'key', b'this')
def score(pt):
    s = sum(1 for b in pt if 32 <= b < 127 or b in (9, 10, 13)) / max(1, len(pt))
    s += sum(0.35 for w in WORDS if w in pt.lower())
    return s

def has_flag(pt):
    return bool(re.search(rb'(?i)(flag|ctf)\\{[^}]{2,80}\\}', pt))

def show(tag, key):
    pt = bytes(b ^ key for b in ct)
    print(f"[*] {tag} key=0x{key:02x}")
    print("[+] plaintext =", pt)
    print("[+] flag-like:", has_flag(pt))
    return has_flag(pt)

found = False
if HINT_KEY:
    found = show("analysis", HINT_KEY[0])
best = max(range(256), key=lambda k: score(bytes(b ^ k for b in ct)))
if not found:
    show("brute force", best)
'''])


def gen_xor_repeating(results, params):
    blob = next((b for b in params["blobs"] if b.get("repeating_xor")), None)
    text = _blob_text(blob) if blob else ""
    hint = b""
    if blob and blob.get("repeating_xor"):
        hint = blob["repeating_xor"][0].get("key", "").encode('latin-1')
    hint_note = _bubble_comment(
        "HINT_KEY was recovered during analysis (inlined the same way an exploit inlines "
        "a resolved address). The script re-derives it independently below as a cross-check; "
        "if the two disagree, one of them is wrong — read both plaintexts.")
    return "\n".join([_HEAD,
                      "# === repeating-key XOR (Hamming shortlist + whole-plaintext hill climbing) ===",
                      "import re", hint_note, f"ct_hex = {text!r}",
                      f"HINT_KEY = {hint!r}",
                      '''
ct = bytes.fromhex(re.sub(r'\\s', '', ct_hex))
WORDS = ('flag','ctf','key','the','and','this','with','for','secret','message',
         'repeating','hamming','distance','xor','attack','plaintext')
FREQ = {'e':12.70,'t':9.06,'a':8.17,'o':7.51,'i':6.97,'n':6.75,'s':6.33,'h':6.09,
        'r':5.99,'d':4.25,'l':4.03,'c':2.78,'u':2.76,'m':2.41,'w':2.36,'f':2.23,
        'g':2.02,'y':1.97,'p':1.93,'b':1.29,'v':0.98,'k':0.77,'j':0.15,'x':0.15,
        'q':0.10,'z':0.07}

def score(data, bonus=True):
    """Mirrors the library scorer. Two rules are load-bearing:
      - the search objective must NOT contain the flag bonus (hill climbing would
        otherwise fabricate a flag-shaped string out of noise)
      - printability alone is far too weak (an earlier version of this script
        returned the wrong key); letter frequency and word hits separate real
        plaintext from printable garbage.
    """
    if not data:
        return -1e9
    text = data.decode('latin-1')
    printable = sum(1 for b in data if 32 <= b < 127 or b in (9, 10, 13)) / len(data)
    s = printable * 60.0
    low = text.lower()
    letters = [c for c in low if 'a' <= c <= 'z']
    if letters:
        freq = 0.0
        for c, pct in FREQ.items():
            obs = low.count(c) / len(letters) * 100.0
            freq -= abs(obs - pct) / 100.0
        s += 30.0 + freq * 10.0
    for run in re.findall(r'[A-Za-z]+', text):
        w = run.lower()
        if len(w) >= 3 and w in WORDS:
            s += 1.5
        elif len(w) >= 4 and not any(v in w for v in 'aeiouy'):
            s -= 1.5
    if bonus and re.search(r'(?i)(flag|ctf)\\{', text):
        s += 60.0
    return s

def decrypt(key):
    return bytes(b ^ key[i % len(key)] for i, b in enumerate(ct))

def has_flag(data):
    return bool(re.search(r'(?i)(flag|ctf)\\{[^}]{2,80}\\}', data.decode('latin-1')))

def refine(key, passes=3):
    key = bytearray(key)
    best = score(decrypt(key), bonus=False)
    for _ in range(passes):
        changed = False
        for i in range(len(key)):
            cur = key[i]
            local, local_s = cur, best
            for g in range(256):
                if g == cur:
                    continue
                key[i] = g
                s = score(decrypt(key), bonus=False)
                if s > local_s + 0.01:
                    local, local_s = g, s
            key[i] = local
            if local != cur:
                best, changed = local_s, True
        if not changed:
            break
    return bytes(key), best

def hamming(a, b):
    return sum(bin(x ^ y).count('1') for x, y in zip(a, b))

# Candidate key lengths: normalised Hamming distance gives a SHORTLIST (the true
# length is often not the top-ranked one); each shortlisted length is refined.
scored = []
for ks in range(1, min(32, len(ct) // 2) + 1):
    blocks = [ct[i * ks:(i + 1) * ks] for i in range(min(8, len(ct) // ks))]
    if len(blocks) < 2:
        continue
    dist = sum(hamming(blocks[i], blocks[i + 1]) / ks
               for i in range(len(blocks) - 1)) / (len(blocks) - 1)
    scored.append((dist, ks))
scored.sort()
shortlist = [ks for d, ks in scored if d <= scored[0][0] + 0.75][:6]
for d, ks in scored:
    if len(shortlist) >= min(6, len(scored)):
        break
    if ks not in shortlist:
        shortlist.append(ks)

best = None
for ks in shortlist:
    key = bytearray()
    for col in range(ks):
        column = bytes(ct[i] for i in range(col, len(ct), ks))
        key.append(max(range(256), key=lambda k: score(bytes(b ^ k for b in column), bonus=False)))
    key, s = refine(key)
    pt = decrypt(key)
    cand = (has_flag(pt), s - 1.0 * ks, key, pt)
    if best is None or cand[:2] > best[:2]:
        best = cand

def show(tag, key):
    pt = decrypt(key)
    print(f"[*] {tag} keylen={len(key)} key={key}")
    print("[+] plaintext =", pt)
    print("[+] flag-like:", has_flag(pt))
    return has_flag(pt)

found = False
if HINT_KEY:
    found = show("analysis", HINT_KEY)
if not found:
    show("independent search", best[2])
'''])


def gen_decode_chain(results, params):
    cands = params["candidates"]["encoding"]
    # `_blob_text` exists for exactly this: `blob["text"]` is display-truncated at 80
    # characters, so inlining it made the generated script decode a shortened ciphertext
    # and print a flag with its tail missing (28 bytes instead of 32) while exiting 0.
    blob = _blob_text(params["blobs"][0]) if params["blobs"] else ""
    return "\n".join([_HEAD, "# === multi-layer decoding (hex/base64/base32/binary) ===",
                      "import base64, codecs, re",
                      f"blob = {blob!r}",
                      _bubble_comment(f"cryptoexp's best guess at the layer order: "
                                      f"{cands[0]['attack'] if cands else 'undetermined'}"),
                      '''
def layers(s):
    out = []
    for _ in range(4):
        t = re.sub(r'\\s', '', s)
        nxt = None
        if re.fullmatch(r'[0-9a-fA-F]+', t or '') and len(t) % 2 == 0:
            try:
                nxt = bytes.fromhex(t)
            except ValueError:
                nxt = None
        if nxt is None:
            try:
                nxt = base64.b64decode(t + '=' * (-len(t) % 4), validate=True)
            except Exception:
                nxt = None
        if not nxt:
            break
        out.append(nxt)
        try:
            s = nxt.decode('ascii')
        except UnicodeDecodeError:
            break
    return out

for i, layer in enumerate(layers(blob), 1):
    print(f"[+] layer {i}:", layer[:120])
'''])


def gen_classical(results, params):
    cands = params["candidates"]["classical"]
    probes = (results.get("classical") or {}).get("probes") or []
    # Inline the real ciphertext (full text, not the display-truncated probe text).
    # No demo fallback: a missing ciphertext means the template cannot solve anything,
    # and a script that prints a hardcoded "Khoor Zruog" translation looks like it
    # worked. Better to emit an honest skeleton that says what to paste.
    cipher = probes[0].get("full_text") if probes else ""
    if not cipher:
        return "\n".join([
            _HEAD, "# === [skeleton] classical cipher, no ciphertext found ===",
            _bubble_comment(
                "the analyzer found no usable ciphertext in the statement, so this "
                "template has nothing to brute force. Paste the text below (or point "
                "the CLI at the file that contains it) and rerun."),
            "CT = ''",
            "",
            "raise SystemExit('[skeleton] fill in CT with the ciphertext and rerun')",
        ])
    # Pick the candidate the analyzer actually believes, not simply the first one: for
    # the Vigenere sample the list starts with a low-score affine candidate, so index 0
    # routed the script to an affine brute force that never finds the flag.
    ranked = sorted(cands, key=lambda c: (
        bool(c.get("flags")), c.get("score") if c.get("score") is not None else -1,
        {"high": 3, "medium": 2, "low": 1}.get(c.get("confidence"), 0)), reverse=True)
    attack = ranked[0]["attack"] if ranked else "caesar"
    hint = _bubble_comment(
        "the analyzer's best candidate was: "
        + (ranked[0].get("detail", "")[:100] if ranked else "undetermined")
        + " -- this script re-derives it from the ciphertext below")
    if attack == "morse":
        return "\n".join([_HEAD, "# === Morse code decoding ===", hint,
                          _MORSE_TABLE_AND_DECODER,
                          f"code = {cipher!r}",
                          "print('[+] plaintext =', morse_decode(code))"])
    if attack == "caesar":
        return "\n".join([_HEAD, "# === Caesar brute force (all 25 shifts, scored) ===",
                          hint, _CAESAR_AND_SCORE,
                          f"ct = {cipher!r}",
                          '''
def shift(s, n):
    out = []
    for ch in s:
        if ch.isupper():
            out.append(chr((ord(ch) - 65 - n) % 26 + 65))
        elif ch.islower():
            out.append(chr((ord(ch) - 97 - n) % 26 + 97))
        else:
            out.append(ch)
    return ''.join(out)

for n in sorted(range(26), key=lambda k: -score(shift(ct, k)))[:3]:
    print(f"[+] shift={n:2d} -> {shift(ct, n)}")
'''])
    if attack == "affine":
        return "\n".join([_HEAD, "# === Affine cipher brute force (a coprime to 26) ===", _CAESAR_AND_SCORE,
                          "import math", f"ct = {cipher!r}",
                          '''
def dec(s, a, b):
    inv = pow(a, -1, 26)
    out = []
    for ch in s:
        if ch.isalpha():
            base = 65 if ch.isupper() else 97
            out.append(chr(((ord(ch) - base - b) * inv) % 26 + base))
        else:
            out.append(ch)
    return ''.join(out)

cands = [(score(dec(ct, a, b)), a, b, dec(ct, a, b))
         for a in range(1, 26) if math.gcd(a, 26) == 1 for b in range(26)]
for sc, a, b, pt in sorted(cands, reverse=True)[:3]:
    print(f"[+] a={a} b={b} -> {pt}")
'''])
    if attack == "vigenere":
        # The inline IoC + per-column chi-square search alone picks the wrong key on
        # this corpus (it recovered "bunribgahfecced" for a "secret" key, exit 0 and no
        # flag). The library's `vigenere_recover` is the tested implementation - three
        # real bugs are encoded in its history - so the template calls it and keeps the
        # inline method only as a fallback for a machine without cryptoexp installed.
        return "\n".join([
            _HEAD, "# === Vigenere recovery ===", hint,
            f'import sys; sys.path.insert(0, r"{_reporoot()}")',
            f"ct = {cipher!r}",
            "",
            "try:",
            "    from cryptoexp.utils.encoding import vigenere_recover",
            "except ImportError:",
            "    vigenere_recover = None",
            "",
            "if vigenere_recover is not None:",
            "    for cand in vigenere_recover(ct)[:3]:",
            "        print(f\"[+] key={cand['key']!r} len={cand['keylen']} \"",
            "              f\"score={cand['score']} -> {cand['plaintext']}\")",
            "else:",
            "    print('[-] cryptoexp is not importable; using the inline fallback')",
            _VIGENERE_FALLBACK_BODY,
        ])
    # fence / fallback
    return "\n".join([_HEAD, "# === Rail fence cipher brute force ===", _CAESAR_AND_SCORE,
                      f"ct = {cipher!r}",
                      '''
def fence_dec(s, rails):
    if rails <= 1 or rails >= len(s):
        return s
    pattern = list(range(rails)) + list(range(rails - 2, 0, -1))
    idx = [pattern[i % len(pattern)] for i in range(len(s))]
    chunks, pos = [], 0
    for r in range(rails):
        n = idx.count(r)
        chunks.append(list(s[pos:pos + n]))
        pos += n
    cur, out = [0] * rails, []
    for r in idx:
        out.append(chunks[r][cur[r]])
        cur[r] += 1
    return ''.join(out)

for rails in sorted(range(2, 9), key=lambda r: -score(fence_dec(ct, r)))[:3]:
    print(f"[+] rails={rails} -> {fence_dec(ct, rails)}")
'''])


_CAESAR_AND_SCORE = '''
WORDS = ('flag', 'ctf', 'the', 'and', 'key', 'this', 'with')

def score(s):
    ls = [c for c in s.lower() if c.isalpha()]
    if not ls:
        return 0.0
    sc = sum(0.6 for w in WORDS if w in s.lower())
    for c, pct in {'e':12.7,'t':9.06,'a':8.17,'o':7.51,'i':6.97,'n':6.75,'s':6.33,
                   'h':6.09,'r':5.99,'d':4.25,'l':4.03,'c':2.78,'u':2.76,'m':2.41,
                   'w':2.36,'f':2.23,'g':2.02,'y':1.97,'p':1.93,'b':1.29,'v':0.98,
                   'k':0.77,'j':0.15,'x':0.15,'q':0.10,'z':0.07}.items():
        sc -= abs(ls.count(c) / len(ls) * 100 - pct) / 100
    return sc
'''

_MORSE_TABLE_AND_DECODER = '''
TABLE = {'.-':'A','-...':'B','-.-.':'C','-..':'D','.':'E','..-.':'F','--.':'G','....':'H',
         '..':'I','.---':'J','-.-':'K','.-..':'L','--':'M','-.':'N','---':'O','.--.':'P',
         '--.-':'Q','.-.':'R','...':'S','-':'T','..-':'U','...-':'V','.--':'W','-..-':'X',
         '-.--':'Y','--..':'Z','-----':'0','.----':'1','..---':'2','...--':'3','....-':'4',
         '.....':'5','-....':'6','--...':'7','---..':'8','----.':'9'}

def morse_decode(s):
    return ' '.join(''.join(TABLE.get(t, '?') for t in w.split())
                    for w in s.replace('/', ' | ').split('|') if w.strip())
'''


# ────────────────────────── number theory / lattice / symmetric ──────────────────────────

def gen_lcg(results, params):
    lcg = params["lcg"] or {}
    states = lcg.get("observed") or []
    return "\n".join([_HEAD, "# === LCG parameter recovery + next-term prediction ===",
                      f"observed = {states}",
                      '''
from math import gcd

def recover(xs, m):
    for i in range(len(xs) - 2):
        d1 = (xs[i + 1] - xs[i]) % m
        d2 = (xs[i + 2] - xs[i + 1]) % m
        try:
            inv = pow(d1, -1, m)
        except ValueError:
            continue
        a = d2 * inv % m
        c = (xs[i + 1] - a * xs[i]) % m
        if all((a * xs[j] + c) % m == xs[j + 1] % m for j in range(len(xs) - 1)):
            return a, c
    return None

# estimate the modulus from gcd of the differences when it is unknown
diffs = [observed[i + 1] - observed[i] for i in range(len(observed) - 1)]
d2 = [diffs[i + 1] * diffs[i - 1] - diffs[i] * diffs[i] for i in range(1, len(diffs) - 1)]
m = 0
for v in d2:
    m = gcd(m, abs(v))
print("[*] estimated modulus m =", m)
rec = recover(observed, m)
if rec:
    a, c = rec
    print("[+] a =", a, " c =", c)
    print("[+] next term =", (a * observed[-1] + c) % m)
'''])


def gen_knapsack(results, params):
    ks = params["knapsack"] or {}
    root = _reporoot()
    picks = ks.get("picks")
    target = ks.get("target")
    if isinstance(target, str) and target.isdigit():
        target = int(target)
    # The weights are not carried in params; re-use the analyzer's own extraction so the
    # script and the verdict can never disagree about which numbers form the knapsack.
    from .analysis.lattice_analysis import _knapsack_inputs
    weights, parsed_target = _knapsack_inputs(results.get("_ctx") or {})
    weights = list(weights or [])
    if target is None:
        target = parsed_target
    head = ["# === low-density subset sum (LLL) ===",
            _bubble_comment(f"cryptoexp verdict: {ks.get('n_items', '?')} items, "
                            f"density {ks.get('density', '?')}, "
                            f"solved indices {ks.get('picks')}")]
    if picks and weights and target is not None:
        # The analyzer solved this sample already (picks came out of the LLL pass), so
        # emitting a fill-in-the-blanks skeleton threw that away. Re-derive here and
        # verify the sum, so the script is self-contained evidence rather than a hint.
        return "\n".join([
            _HEAD] + head + [
            f'import sys; sys.path.insert(0, r"{root}")',
            "from cryptoexp.utils.lattice import subset_sum_lll",
            f"WEIGHTS = {list(weights)!r}",
            f"TARGET = {target!r}",
            "",
            "picks = subset_sum_lll(WEIGHTS, TARGET)",
            "if picks is None:",
            "    raise SystemExit('[-] LLL found no subset; try the meet-in-the-middle route')",
            "picks = sorted(picks)",
            "assert sum(WEIGHTS[i] for i in picks) == TARGET, 'the subset does not sum to TARGET'",
            "print('[+] selected indices:', picks)",
            "print('[+] subset sum      :', sum(WEIGHTS[i] for i in picks))",
        ])
    # No solved picks to reuse: be explicit that this is a skeleton, and say what to do.
    return "\n".join([
        _HEAD, "# === [skeleton] low-density subset sum (LLL) ==="] + head + [
        f'import sys; sys.path.insert(0, r"{root}")',
        "from cryptoexp.utils.lattice import subset_sum_lll",
        "# weights = [...]   # <- replace with the challenge knapsack",
        "# target = 0        # <- replace with the target sum",
        "raise SystemExit('[skeleton] fill in weights / target and rerun')",
    ])


def gen_ecb_detect(results, params):
    sym = params["symmetric"]
    data = None
    ctx_data = (results.get("_ctx") or {}).get("data") or []
    for item in ctx_data:
        if len(item.get("data", b"")) >= 32:
            data = item
            break
    hexstr = data["data"].hex() if data else ""
    return "\n".join([_HEAD, "# === ECB mode detection (repeated blocks) ===", "import re",
                      _bubble_comment(f"cryptoexp verdict: mode={sym.get('mode')}, "
                                      f"block_size={sym.get('block_size')}, "
                                      f"{len(sym.get('repeated_blocks', []))} repeated block groups"),
                      f"ct_hex = {hexstr!r}  # may be truncated, prefer the full ciphertext",
                      '''
ct = bytes.fromhex(re.sub(r'\\s', '', ct_hex))
for bs in (16, 8, 32):
    blocks = [ct[i:i + bs] for i in range(0, len(ct) - bs + 1, bs)]
    dups = {b: blocks.count(b) for b in set(blocks) if blocks.count(b) > 1}
    if dups:
        print(f"[+] block_size={bs}, {len(dups)} repeated block groups -> ECB")
        for b, n in list(dups.items())[:3]:
            print("    ", b.hex(), "x", n)
        break
else:
    print("[-] no repeated blocks -> not ECB (or the ciphertext is too short)")
'''])


def gen_cbc_skeleton(results, params):
    return "\n".join([
        _HEAD, "# === CBC bit flipping / padding oracle — [skeleton] ===",
        _bubble_comment(
            "Static analysis cannot finish a CBC exploit: it needs interaction with a server oracle.\n"
            "Bit flipping in short: to change byte j of plaintext block k, flip byte j of the\n"
            "previous ciphertext block:\n"
            "    ct_prev[j] ^= old_plain[j] ^ want_plain[j]\n"
            "Padding oracle in short: brute force from the last byte backwards, one plaintext byte\n"
            "per round; the branch that says 'padding is valid' gives the intermediate value for\n"
            "that byte, which you then XOR with the target padding."),
        "from pwn import remote, xor  # usable directly if pwntools is installed",
        "# io = remote('host', port)",
        "# 1) find block_size first (submit ciphertexts of growing length, watch the length jump)",
        "# 2) grab iv + ct (usually base64/hex encoded, decode them first)",
        "# 3) recover the intermediate value byte by byte as noted above, then rebuild plaintext/forgery",
        "raise SystemExit('skeleton: needs the oracle address and encoding')",
    ])


def gen_placeholder(results, params):
    ctx = results.get("_ctx") or {}
    named = ctx.get("named", {})
    lines = [_HEAD, "# === no automated route matched — [skeleton] ===",
             _bubble_comment("None of cryptoexp's usual attack surfaces matched. Parameters "
                             "extracted so far are below; write the attack by hand from them.")]
    for k, vs in named.items():
        lines.append(f"# {k} = {vs[0] if len(vs) == 1 else vs}")
    lines.append(f"# challenge text length: {len(ctx.get('raw_text', ''))} characters")
    lines.append("raise SystemExit('skeleton: needs an extra leak or a manual idea')")
    return "\n".join(lines)


# ────────────────────────── registration and routing ──────────────────────────

def _register_builtins():
    def P(fn):
        return fn

    def has(params_key):
        return lambda r: bool(_params(r).get(params_key))

    register_solver("rsa_direct",
                    lambda r: (lambda p: bool((p.get("p") and p.get("q"))
                                              or p.get("d")
                                              or p.get("phi") or p.get("phi_n")))(_params(r)),
                    gen_rsa_direct, priority=10)
    register_solver("rsa_dp_leak", lambda r: bool(_params(r).get("dp") and _params(r).get("c")),
                    gen_rsa_dp_leak, priority=15)
    register_solver("rsa_shared_prime",
                    lambda r: len({v for v in _params(r)["n_list"] if v}) >= 2
                              and any(v.get("attack") == "shared_prime"
                                      for v in (r.get("rsa") or {}).get("vulns", [])),
                    gen_rsa_shared_prime, priority=20)
    register_solver("rsa_small_e",
                    lambda r: any(v.get("attack") == "small_e_root"
                                  for v in (r.get("rsa") or {}).get("vulns", [])),
                    gen_rsa_small_e, priority=22)
    register_solver("rsa_broadcast",
                    lambda r: any(v.get("attack") == "low_exponent_broadcast"
                                  for v in (r.get("rsa") or {}).get("vulns", [])),
                    gen_rsa_broadcast, priority=25)
    register_solver("rsa_wiener",
                    lambda r: any(v.get("attack") == "wiener"
                                  for v in (r.get("rsa") or {}).get("vulns", [])),
                    gen_rsa_wiener, priority=30)
    register_solver("rsa_fermat",
                    lambda r: any(v.get("attack") == "fermat"
                                  for v in (r.get("rsa") or {}).get("vulns", [])),
                    gen_rsa_fermat, priority=35)
    register_solver("rsa_factor",
                    lambda r: any(v.get("attack") == "factor"
                                  for v in (r.get("rsa") or {}).get("vulns", [])),
                    gen_rsa_factor, priority=40)
    register_solver("rsa_coppersmith",
                    lambda r: bool((r.get("lattice") or {}).get("coppersmith")),
                    gen_rsa_coppersmith, priority=45)
    # Order matters here: a single-byte ciphertext also satisfies the repeating-key
    # predicate (a 2-byte periodic key decrypts it), but only this template is the
    # direct answer — and a genuine multi-byte ciphertext never yields a flag from
    # the single-byte attack, so the fallback order stays correct.
    register_solver("xor_single",
                    lambda r: any(
                        _hex_ciphertext(b) and (
                            ((b.get("xor") or [{}])[0].get("top") or [{}])[0].get("flags")
                            or ((b.get("xor") or [{}])[0].get("top") or [{}])[0].get("score", 0) >= 95)
                        for b in (r.get("encoding") or {}).get("blobs", [])),
                    gen_xor_single, priority=58)
    register_solver("xor_repeating",
                    lambda r: any(
                        _hex_ciphertext(b) and (
                            (b.get("repeating_xor") or [{}])[0].get("flags")
                            or (b.get("repeating_xor") or [{}])[0].get("score", 0) >= 90)
                        for b in (r.get("encoding") or {}).get("blobs", [])),
                    gen_xor_repeating, priority=60)
    # A decode chain is only worth a template when it actually produced a flag or a
    # top-confidence decode; otherwise it shadows the classical-cipher route
    # (observed on the Caesar sample, which routed here and could not solve itself).
    register_solver("decode_chain",
                    lambda r: any(
                        ((b.get("chain") or [{}])[0]).get("flags")
                        or ((b.get("chain") or [{}])[0]).get("confidence") == "high"
                        for b in (r.get("encoding") or {}).get("blobs", [])),
                    gen_decode_chain, priority=64)
    register_solver("classical",
                    lambda r: bool((r.get("classical") or {}).get("candidates")),
                    gen_classical, priority=66)
    register_solver("lcg",
                    lambda r: bool((r.get("numbertheory") or {}).get("lcg")),
                    gen_lcg, priority=70)
    register_solver("knapsack",
                    lambda r: bool((r.get("lattice") or {}).get("knapsack")),
                    gen_knapsack, priority=72)
    register_solver("ecb_detect",
                    lambda r: (r.get("symmetric") or {}).get("mode") == "ECB",
                    gen_ecb_detect, priority=80)
    register_solver("cbc_padding_oracle",
                    lambda r: any(v.get("attack") in ("cbc_bitflip", "padding_oracle")
                                  for v in (r.get("symmetric") or {}).get("vulns", [])),
                    gen_cbc_skeleton, priority=85)
    register_solver("crc_preimage",
                    lambda r: any(c.get("attack") == "crc_preimage"
                                  for c in (r.get("crc") or {}).get("candidates", [])),
                    gen_crc_preimage, priority=40)
    register_solver("lfsr",
                    lambda r: any(c.get("attack") in ("lfsr_keystream", "lfsr_predict")
                                  for c in (r.get("lfsr") or {}).get("candidates", [])),
                    gen_lfsr, priority=42)
    register_solver("placeholder", lambda r: True, gen_placeholder, priority=999)


# ────────────────────────── CRC / LFSR templates ──────────────────────────

def gen_crc_preimage(results, params):
    """Standalone CRC preimage solver: GF(2) linear algebra, no toolkit import"""
    crc = params.get("crc") or {}
    prm = crc.get("params") or {}
    width = prm.get("width") or 32
    poly = prm.get("poly") or 0x04C11DB7
    init = prm.get("init", 0)
    xorout = prm.get("xorout", 0)
    refin = bool(prm.get("refin", False))
    refout = bool(prm.get("refout", False))
    cand = next((c for c in crc.get("candidates", [])
                 if c.get("attack") == "crc_preimage"), None)
    data = (cand or {}).get("data") or b""
    hint = _bubble_comment(
        "the analyzer recovered " + repr(data) + " by solving CRC(prefix||x||suffix)=target\n"
        "this script redoes that solve from the statement values, without trusting it")
    return f'''#!/usr/bin/env python3
"""CRC preimage via GF(2) linear algebra (generated by cryptoexp).

CRC is affine over GF(2), so a fixed-length unknown field is a linear system:
CRC(prefix || x || suffix) == target is solved, not brute forced.
"""
{hint}

WIDTH = {width}
POLY = {poly:#x}
INIT = {init:#x}
XOROUT = {xorout:#x}
REFIN = {refin}
REFOUT = {refout}


def crc(data, width=WIDTH, poly=POLY, init=INIT, refin=REFIN, refout=REFOUT,
        xorout=XOROUT):
    mask = (1 << width) - 1
    top = 1 << (width - 1)
    reg = init
    for byte in data:
        if refin:
            byte = int(f"{{byte:08b}}"[::-1], 2)
        for i in range(7, -1, -1):
            reg ^= ((byte >> i) & 1) << (width - 1)
            reg = ((reg << 1) ^ poly) & mask if reg & top else (reg << 1) & mask
    if refout:
        reg = int(f"{{reg:0{{width}}b}}"[::-1], 2)
    return reg ^ xorout


def solve(prefix, suffix, target, unknown_len):
    n_bits = 8 * unknown_len
    tail = bytes(unknown_len)
    base = crc(prefix + tail + suffix)
    rhs = [(target ^ base) >> i & 1 for i in range(WIDTH)]
    rows = [0] * WIDTH
    for j in range(n_bits):
        probe = bytearray(tail)
        probe[j // 8] |= 1 << (j % 8)
        column = crc(prefix + bytes(probe) + suffix) ^ base
        for i in range(WIDTH):
            if column >> i & 1:
                rows[i] |= 1 << j
    # Gaussian elimination over GF(2)
    aug = [rows[i] | (rhs[i] << n_bits) for i in range(WIDTH)]
    pivot_row = 0
    where = [-1] * n_bits
    for col in range(n_bits):
        sel = next((r for r in range(pivot_row, WIDTH) if aug[r] >> col & 1), None)
        if sel is None:
            continue
        aug[pivot_row], aug[sel] = aug[sel], aug[pivot_row]
        for r in range(WIDTH):
            if r != pivot_row and (aug[r] >> col & 1):
                aug[r] ^= aug[pivot_row]
        where[col] = pivot_row
        pivot_row += 1
    if any((aug[r] & ((1 << n_bits) - 1)) == 0 and (aug[r] >> n_bits & 1)
           for r in range(WIDTH)):
        return None
    x = 0
    for col in range(n_bits):
        if where[col] != -1 and (aug[where[col]] >> n_bits & 1):
            x |= 1 << col
    out = bytearray(unknown_len)
    for j in range(n_bits):
        if x >> j & 1:
            out[j // 8] |= 1 << (j % 8)
    return bytes(out)


def main():
    prefix = {params.get("crc_prefix", b"")!r}
    suffix = {params.get("crc_suffix", b"")!r}
    target = {params.get("crc_target", 0)!r}
    unknown_len = {params.get("crc_unknown_len", 0)!r}
    unknown = solve(prefix, suffix, target, unknown_len)
    if unknown is None:
        raise SystemExit("[-] no assignment of the unknown bytes reaches this CRC")
    full = prefix + unknown + suffix
    assert crc(full) == target, "internal check failed"
    print("[+] unknown bytes:", unknown)
    print("[+] full message:", full)


if __name__ == "__main__":
    main()
'''


def gen_lfsr(results, params):
    """Standalone LFSR template: recover the taps (or use the given ones), predict"""
    lfsr = params.get("lfsr") or {}
    prm = lfsr.get("params") or {}
    taps = prm.get("taps")
    state = prm.get("state")
    bits = prm.get("observed_run") or ""
    ct_hexes = prm.get("ciphertexts_hex") or ([prm["ciphertext_hex"]]
                                              if prm.get("ciphertext_hex") else [])
    hint = _bubble_comment(
        "analyzer notes: " + "; ".join(lfsr.get("notes") or ["(none)"]))
    taps_lit = repr(taps)
    return f'''#!/usr/bin/env python3
"""LFSR keystream recovery (generated by cryptoexp).

Two paths, both mechanical:
  * taps given  -> run the register forward;
  * taps unknown -> Berlekamp-Massey recovers the recurrence from >= 2L output bits,
    then the continuation is deterministic.
"""
{hint}

TAPS = {taps_lit}
STATE = {state!r}
OBSERVED_BITS = {bits!r}
CIPHERTEXTS_HEX = {ct_hexes!r}


def berlekamp_massey(bits):
    """Minimal recurrence: returns the exponent list including the leading term"""
    n = len(bits)
    C = [1] + [0] * n
    B = [1] + [0] * n
    L, m = 0, 1
    for i in range(n):
        d = bits[i]
        for j in range(1, L + 1):
            d ^= C[j] & bits[i - j]
        if d == 0:
            m += 1
            continue
        T = C[:]
        for j in range(m, n + 1):
            C[j] ^= B[j - m]
        if 2 * L <= i:
            L, B, m = i + 1 - L, T, 1
        else:
            m += 1
    return [i for i, c in enumerate(C[:L + 1]) if c and i > 0]


def lfsr_stream(taps, state, count):
    """Emit `count` bits from a Galois LFSR: bit 0 is emitted first

    Same step as cryptoexp.utils.gf2.LFSR.next_bit: emit state bit 0, shift right, and
    shift the parity of the tapped bits into the top. `taps` includes the leading term,
    so every tap except the last one is XORed into the feedback.
    """
    L = max(taps) if taps else 0
    if L == 0:
        return [0] * count
    mask = 0
    for t in taps[:-1]:
        mask |= 1 << t
    out = []
    for _ in range(count):
        bit = state & 1
        fb = (state & mask).bit_count() & 1
        state = (state >> 1) | (fb << (L - 1))
        out.append(bit)
    return out


def state_from_bits(bits):
    """Register whose bit 0 is bits[0] - the first bit the register emits"""
    state = 0
    for i, b in enumerate(bits):
        state |= (b & 1) << i
    return state


def bits_to_bytes(bits):
    out = bytearray()
    for i in range(0, len(bits) - len(bits) % 8, 8):
        byte = 0
        for b in bits[i:i + 8]:
            byte = (byte << 1) | b
        out.append(byte)
    return bytes(out)


def main():
    observed = [int(c) for c in OBSERVED_BITS]
    if observed:
        taps = list(TAPS) if TAPS else berlekamp_massey(observed)
        if not taps:
            raise SystemExit("[-] Berlekamp-Massey found no recurrence")
        L = max(taps)
        if len(observed) < 2 * L:
            raise SystemExit("[-] not enough observed bits for a unique recurrence")
        state = state_from_bits(observed[:L])
        if lfsr_stream(taps, state, len(observed)) != observed:
            raise SystemExit("[-] the recovered register does not replay the observation")
        print("[*] taps:", taps, "(register length", L, ")")
    elif TAPS and STATE is not None:
        taps, state = list(TAPS), STATE
        print("[*] taps given explicitly:", taps)
    else:
        raise SystemExit("[-] need either the observed bits or (taps, state)")

    # Every decoded blob is tried: the statement's bit run is also decoded as "hex"
    # by the context, so one of the blobs is usually not the real ciphertext.
    for hex_ct in CIPHERTEXTS_HEX:
        ct = bytes.fromhex(hex_ct)
        want = max(8 * len(ct), 8 * 8)
        stream_bits = lfsr_stream(taps, state, len(observed) + want)[len(observed):]
        stream = bits_to_bytes(stream_bits)
        plaintext = bytes(a ^ b for a, b in zip(ct, stream))
        print(f"[+] keystream XOR of blob len {{len(ct)}}:", plaintext)
    if not CIPHERTEXTS_HEX:
        print("[+] predicted bytes:", bits_to_bytes(
            lfsr_stream(taps, state, len(observed) + 64)[len(observed):]))


if __name__ == "__main__":
    main()
'''


def generate(results: dict, out_dir: str = "solves", only: str = None) -> str:
    """Route by priority, generate the solve script -> returns the written path"""
    global _BUILTINS_LOADED
    if not _BUILTINS_LOADED:
        _register_builtins()
        _BUILTINS_LOADED = True

    params = _params(results)
    picked = None
    for s in _SOLVERS:
        if only and s["name"] != only:
            continue
        try:
            if s["predicate"](results):
                picked = s
                break
        except Exception:
            continue
    if picked is None:
        picked = {"name": "placeholder", "gen": gen_placeholder}

    script = picked["gen"](results, params)
    os.makedirs(out_dir, exist_ok=True)
    name = (results.get("target") or "target")
    base = os.path.basename(str(name).rstrip("\\/")) or "target"
    base = "".join(ch for ch in base if ch.isalnum() or ch in "._-") or "target"
    path = os.path.join(out_dir, f"solve_{picked['name']}_{base}.py")
    with open(path, 'w', encoding='utf-8') as f:
        f.write(script)
    return path
