"""Forensics for real deployments - key audits, captured tokens and wire material

This is the layer a penetration tester or a security researcher points at material
that came *out of the world* rather than out of a challenge file: a dump of a
TLS/SSH/embedded fleet's RSA moduli, a DER-encoded ECDSA signature lifted from
X.509 or from captured protocol traffic, a JWS/JWT pasted from a bug bounty
target, a stream of "random" session tokens. Every function here answers one
question that ends up in a report - "which hosts share a prime?", "is that
signature worth an offline nonce-reuse attempt?", "does this service accept
alg=none?", "is this key reachable by an attack we can actually run?", "are those
tokens generated by a linear congruential generator?" - and none of them prints,
mutates global state, or raises on an ordinary negative answer.

Conventions used throughout:

    * explicit parameters, plain dicts/lists/tuples out;
    * "I looked and found nothing" is a normal result (empty list, ok=False, or a
      note), never an exception;
    * "this input is not what you say it is" is a ValueError;
    * no check is ever skipped silently - the audit's `checked` field and the
      fingerprint's `tried` field record every check and why it did not run.

Everything is hand-rolled on the standard library and reuses the lower layers
(`algebra`, `modular`, `rsa_ops`, `keys`, `prng`, `prng_extra`) rather than
duplicating them.
"""

import base64
import json
import math

from . import algebra as A
from . import keys as K
from . import modular as M
from . import prng as PR
from . import prng_extra as PE
from . import rsa_ops as R

__all__ = [
    "batch_gcd",
    "common_factor_pairs",
    "parse_der_signature",
    "parse_jwt",
    "audit_rsa_key",
    "detect_weak_prng",
]

_MASK32 = 0xffffffff
_MASK48 = (1 << 48) - 1
_JAVA_MAGIC = 0x5deece66d
_JAVA_ADDEND = 0xb
_MT_MIN_WORDS = 624
_B64URL_CHARS = frozenset(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_="
)
_SEVERITY_ORDER = ("critical", "high", "medium", "low", "info")


# ------------------------------------------------------------------ batch GCD

def batch_gcd(moduli, progress=None):
    """Find every pair of RSA moduli that share a prime factor, in near-linear time

    Why a tester needs it: a fleet-wide key audit ("we dumped every public key in
    the estate / every certificate the load balancer served / every SSH host key")
    is decided by this one question. Two moduli sharing a prime means both private
    keys are recoverable by a single gcd, and the root cause is almost always a
    weak or forked RNG at manufacturing time (Debian OpenSSL, embedded devices
    with no entropy at first boot, a VM image cloned with its seed). The naive
    answer is the O(n^2) double loop, which for the 30,000-modulus dumps a
    researcher actually collects is ~450 million big-integer gcds - hours. The
    product/remainder tree below makes it practical: build the product of all
    moduli, propagate remainders down so that vertex i receives the product of
    every *other* modulus, then one gcd per modulus exposes each shared factor.
    Every reported factor is verified by division before it is returned, so the
    result is exact - there are no probabilistic "candidates" here.

    Complexity (big-integer operations, taking the moduli as n numbers of L bits):
        build the product tree   O(n * L) bit operations per level, O(log n) levels
        one root remainder       O(M(nL) * log(nL)) for a single nL-bit value
        remainder tree + gcds    ~2n modular reductions and n gcds, same order
        overall quasi-linear     ~O(n * L^2) bit operations (the gcd-avoidance
                                 result of Bernstein), i.e. n log^2 n word
                                 operations, versus O(n^2) for the naive loop.
    Space is the two trees: O(n * L) bits (~2x the root product), so a 40,000-key
    audit at 2048 bits stays in the low tens of MB.

    Args:
        moduli: iterable of positive ints (bytes are accepted and read big-endian).
            Values <= 1 are not keys and are skipped; their indices are reported
            in `skipped`, not silently dropped.
        progress: optional callable(status: str) invoked at the phase boundaries
            (it is an observability hook, not a status line the library prints).

    Returns:
        {
          "pairs":  [{"i": int, "j": int, "factor": int}, ...] sorted by (i, j),
                    one entry per unordered index pair sharing a factor;
          "checked": int - how many moduli took part,
          "groups": {factor: [indices, ...]} - every index that shares that factor,
          "skipped": [index, ...] - entries that were <= 1 or unparsable,
          "rejected": [{"factor", "indices"}, ...] - candidates that failed the
                      division check (always empty unless the tree math is wrong),
          "note": str - "" when nothing was found, otherwise what was found.
        }

    `groups` maps one integer factor to the sorted list of indices that share it, so
    it serialises straight to JSON (the keys become strings there). The factor is
    canonical: a bucket's key is the gcd of its members, so the same finding is not
    also reported under a composite multiple of it.
    """
    raw = list(moduli)
    ns = []
    skip = []
    for idx, value in enumerate(raw):
        if isinstance(value, (bytes, bytearray)):
            value = R.bytes_to_long(value)
        try:
            n = int(value)
        except (TypeError, ValueError):
            skip.append(idx)
            continue
        if n <= 1:
            skip.append(idx)
            continue
        ns.append((idx, n))

    if progress:
        progress("batch_gcd: %d usable moduli, building the product tree" % len(ns))

    out = {"pairs": [], "checked": len(ns), "groups": {}, "duplicates": {},
           "skipped": skip, "note": ""}
    if len(ns) < 2:
        out["note"] = "fewer than two usable moduli: nothing to compare"
        return out

    indices = [i for i, _ in ns]
    values = [n for _, n in ns]
    value_of = dict(zip(indices, values))

    # Duplicate moduli are their own finding: two "different" keys that are the same
    # key means one key pair was handed out twice. Reported separately because a
    # shared modulus is not a shared prime - gcd(n, n) = n, which would otherwise
    # surface as a "factor" equal to the modulus itself and mislead the caller.
    by_value = {}
    for idx, n in zip(indices, values):
        by_value.setdefault(n, []).append(idx)
    duplicates = {n: sorted(idxs) for n, idxs in by_value.items() if len(idxs) > 1}
    out = {"pairs": [], "checked": len(ns), "groups": {}, "duplicates": duplicates,
           "skipped": skip, "note": ""}
    if duplicates:
        out["note"] = "%d duplicate modulus(es) found" % len(duplicates)
    if len(ns) < 2:
        out["note"] = "fewer than two usable moduli: nothing to compare"
        return out

    # Product tree, root first; see `_product_tree` and `_remainder_tree` for why the
    # shape is root-first and why the descent squares each node value.
    levels = _product_tree(values)

    if progress:
        progress("batch_gcd: remainder tree")

    cur = _remainder_tree(levels)
    if progress:
        progress("batch_gcd: %d gcd tests" % len(values))

    buckets = {}
    for pos, idx in enumerate(indices):
        # cur[pos] is the product of every other modulus, reduced modulo this one, so
        # gcd > 1 means this modulus shares a factor with at least one other.
        g = A.gcd(values[pos], cur[pos])
        if g > 1:
            buckets.setdefault(g, set()).add(idx)

    # A factor can show up under several keys (the minimal gcd of a subset and,
    # separately, the full modulus of a duplicate). Merge keys that are not
    # coprime, then each bucket becomes exactly one canonical factor.
    keys = sorted(buckets)
    merged = []
    for key in keys:
        members = buckets[key]
        for entry in merged:
            if A.gcd(entry[0], key) > 1:
                entry[0] = A.gcd(entry[0], key)
                entry[1] |= members
                break
        else:
            merged.append([key, set(members)])

    groups = {}
    pairs = []
    rejected = []
    for factor, members in merged:
        if len(members) < 2:
            continue
        ordered = sorted(members)
        # Confirm by division before reporting. The remainder tree makes this true by
        # construction, so a failure here would mean the tree math is wrong: it is a
        # cheap, independent check that "we computed it" is really "it divides", and it
        # keeps a broken construction from ever reaching a report as a finding.
        if any(value_of[pos] % factor for pos in ordered):
            rejected.append({"factor": factor, "indices": ordered})
            continue
        groups[factor] = ordered
        for ai in range(len(ordered)):
            for bi in range(ai + 1, len(ordered)):
                pairs.append({"i": ordered[ai], "j": ordered[bi], "factor": factor})
    pairs.sort(key=lambda p: (p["i"], p["j"]))

    out["pairs"] = pairs
    out["groups"] = groups
    out["rejected"] = rejected
    if pairs:
        out["note"] = ("%d shared-factor pair(s) among %d moduli; %d distinct factor(s)"
                       % (len(pairs), len(ns), len(groups)))
    else:
        out["note"] = "no shared factors among %d moduli" % len(ns)
    if rejected:
        out["note"] += ("; %d candidate factor(s) failed the division check and were "
                        "not reported" % len(rejected))
    if progress:
        progress("batch_gcd: done, %d pair(s)" % len(pairs))
    return out


def _product_tree(values):
    """level[0] = the root product of all values, level[-1] = the values themselves

    Written root-first so the remainder descent below can read it straight down. A
    level with an odd count carries its last element up unchanged to the level above:
    that node has no partner to multiply with, and carrying it (rather than padding
    with a 1) keeps every leaf's ancestry honest about which moduli it covers.
    """
    levels = [list(values)]
    while len(levels[0]) > 1:
        top = levels[0]
        prev = [top[k] * top[k + 1] for k in range(0, len(top) - 1, 2)]
        if len(top) % 2:
            prev.append(top[-1])
        levels.insert(0, prev)
    return levels


def _remainder_tree(levels):
    """Descend the product tree -> for each modulus, the product of all the others mod it

    The step that makes a fleet-wide gcd audit practical. `levels[0]` is the whole
    product P (the root), `levels[k]` the nodes k steps below it, and `levels[-1]`
    the moduli themselves. The descent is the classical identity

        R(level)[i] = R(level - 1)[i // 2] mod value(level)[i]^2

    with the root starting at R = P. Squaring the node value is what makes the answer
    exact rather than merely "shares something": because n_i divides P, we have
    P == n_i * (P / n_i), so

        P mod n_i^2 == n_i * ((P / n_i) mod n_i)

    and dividing the leaf result by n_i leaves exactly the product of every *other*
    modulus, reduced modulo n_i - the number whose gcd with n_i is non-trivial
    precisely when n_i shares a factor with another modulus. (Reducing modulo n_i
    instead would send every non-shared modulus to 0 and report the whole fleet as
    weak.)

    The index map `i // 2` is uniform because the tree carries an odd leftover element
    up to the level above, which means the last child of a level and the last element
    of its parent are the same value - so the usual heap-style parent of child i is
    correct for every shape.

    Iterative, one array per level: a 100,000-modulus audit is 17 levels deep and
    never recurses. Cost is one squaring, one reduction and one division per node,
    i.e. O(n) big-integer operations - the same order as building the product tree
    itself, against O(n^2) for the naive double loop.

    Returns a list of `(P / n_i) mod n_i` values aligned with levels[-1] (the moduli,
    in order).
    """
    leaves = levels[-1]
    rem = [levels[0][0]]
    for level in range(1, len(levels)):
        values = levels[level]
        top = rem
        rem = [0] * len(values)
        for pos, value in enumerate(values):
            parent = top[pos // 2]
            if value > 1:
                rem[pos] = parent % (value * value)
            else:
                rem[pos] = 0
    return [rem[pos] // leaves[pos] if leaves[pos] > 1 else 0
            for pos in range(len(leaves))]

def common_factor_pairs(moduli):
    """[(i, j, factor), ...] from `batch_gcd` - the shape a report table wants

    A convenience wrapper only: identical computation, identical verification, just
    unpacked into tuples sorted by (i, j) so the caller can iterate straight into
    "host i and host j share prime p" without dictionary indexing.
    """
    res = batch_gcd(moduli)
    return [(p["i"], p["j"], p["factor"]) for p in res["pairs"]]


# ------------------------------------------------------------------ DER signature

def parse_der_signature(der):
    """Parse SEQUENCE { INTEGER r, INTEGER s } -> {"r": int, "s": int}, else None

    Why a tester needs it: an ECDSA/DSA signature lifted out of an X.509 certificate,
    a JWS field, a TLS handshake or a captured proprietary protocol arrives as raw DER.
    The signature itself is worthless to the analyst - what matters is feeding r and s
    into the nonce-reuse and lattice attacks (`signatures.ecdsa_nonce_reuse`, ...).
    Doing that by hand for every captured blob is where mistakes happen, and the two
    classic parsing traps both live in the INTEGERs: the 0x00 prefix that keeps a
    high-bit value positive, and the long-form length that appears as soon as r is 128
    bytes. Both are handled here.

    The DER TLV reading is delegated to `keys._der_read` / `keys._der_decode_int`, so
    the package has exactly one DER parser rather than two that can drift apart; that
    layer already handles short/long-form lengths, rejects the indefinite form, strips
    the leading 0x00 of a positive INTEGER and refuses a negative one.

    Trailing bytes after the SEQUENCE are rejected: a blob followed by garbage is not a
    bare signature, and silently ignoring the tail is how a parser ends up reporting
    the r/s of some enclosing structure.

    Args:
        der: bytes (or bytearray) of the DER blob.

    Returns:
        {"r": int, "s": int} on a clean parse; None when the structure is not
        SEQUENCE{r, s}. None means "not a bare DER signature", an ordinary answer for
        TLS record bytes or a PEM file that was pasted by mistake. Only a non-bytes
        argument raises.

    Note the shape: PKCS#1 RSAPublicKey is also SEQUENCE{INTEGER, INTEGER}, so a
    two-integer blob is accepted whatever its provenance - this parser reads
    structure, and telling a signature from a public key needs context it does not
    have.
    """
    if isinstance(der, (bytearray, memoryview)):
        der = bytes(der)
    if not isinstance(der, bytes):
        raise ValueError("parse_der_signature expects bytes")
    if not der:
        return None
    try:
        tag, body, end = K._der_read(der, 0)
        if tag != 0x30 or end != len(der):
            return None
        tag_r, raw_r, off = K._der_read(body, 0)
        if tag_r != 0x02:
            return None
        tag_s, raw_s, off = K._der_read(body, off)
        if tag_s != 0x02 or off != len(body):
            return None
        r = K._der_decode_int(raw_r)
        s = K._der_decode_int(raw_s)
    except ValueError:
        return None
    if r <= 0 or s <= 0:
        return None
    return {"r": r, "s": s}

# ------------------------------------------------------------------ JWT / JWS

def _b64url_decode(segment):
    """base64url segment -> bytes, tolerant of missing padding and of -/_"""
    if isinstance(segment, (bytes, bytearray)):
        segment = bytes(segment).decode("ascii", "ignore")
    text = str(segment).strip()
    if not text:
        raise ValueError("empty base64url segment")
    if any(ch not in _B64URL_CHARS for ch in text):
        raise ValueError("segment contains characters outside the base64url alphabet")
    cleaned = text.replace("-", "+").replace("_", "/")
    cleaned += "=" * ((-len(cleaned)) % 4)
    return base64.b64decode(cleaned)


def parse_jwt(token):
    """Split and decode a JWS/JWT - and report the algorithm it *claims* to use

    Why a tester needs it: pasting a bearer token into an engagement note and
    reading its claims (iss, sub, exp, scope, roles) is the fastest way to learn
    what a target trusts. Two findings fall straight out of the header and belong
    in the report: `alg: none` (an unsigned token some stacks still accept) and a
    symmetric algorithm such as HS256, where a gateway that also hands out a public
    key is a signature-forgery finding waiting to happen.

    The signature is deliberately NOT verified. Verification is a policy decision -
    which key, which clock skew, which `alg` list is allowed - and this library's
    job is to hand back the decoded material plus `hmac_sha256` for the caller that
    knows its policy. A function that returned True/False here would be answering a
    question it cannot know the parameters of.

    Args:
        token: str (or ASCII/UTF-8 bytes) of the compact serialisation,
            `base64url(header).base64url(payload)[.base64url(signature)]`.

    Returns:
        {
          "header": dict (empty {} when the first segment is not a JSON object),
          "payload": dict or None,
          "signature": bytes or None,
          "alg": str or None (the header's algorithm, as claimed),
          "typ": str or None,
          "segments": int (1..3 actually present, 0 for an empty token),
          "errors": [str, ...] (what was wrong, in reading order),
          "weak_alg": bool (True for alg "none", for a missing/empty alg, and for
                            any HS* symmetric algorithm),
        }

    Nothing about the *content* raises. This helper gets pointed at log lines, proxy
    dumps and grep results where most strings are not JWTs at all, so anything that
    fails to decode is reported in `errors` with an empty `header` - the caller
    filters on `segments`/`errors` rather than catching exceptions in a loop. Only a
    non-string/None argument raises, because that is a misuse of the API rather than
    a token that did not parse.
    """
    if isinstance(token, (bytes, bytearray)):
        text = bytes(token).decode("ascii", "ignore").strip()
    elif isinstance(token, str):
        text = token.strip()
    else:
        raise ValueError("parse_jwt expects the compact serialisation as a string")

    out = {
        "header": {},
        "payload": None,
        "signature": None,
        "alg": None,
        "typ": None,
        "segments": 0,
        "errors": [],
        "weak_alg": False,
    }
    if not text:
        out["errors"].append("empty token")
        return out

    parts = text.split(".")
    if len(parts) > 3:
        out["errors"].append("token has %d segments (a JWS compact token has 3)"
                             % len(parts))
    if len(parts) == 1:
        out["errors"].append("no '.' separator found: not a compact JWS token")
    out["segments"] = min(len(parts), 3)

    for label, index in (("header", 0), ("payload", 1), ("signature", 2)):
        if index >= len(parts):
            continue
        segment = parts[index]
        if segment == "":
            if label != "signature":
                out["errors"].append("%s segment is empty" % label)
            continue
        try:
            raw = _b64url_decode(segment)
        except Exception as exc:
            out["errors"].append("%s segment does not decode: %s" % (label, exc))
            continue
        if label == "signature":
            out["signature"] = raw
            continue
        try:
            decoded = json.loads(raw.decode("utf-8"))
        except Exception as exc:
            out["errors"].append("%s segment is not JSON: %s" % (label, exc))
            continue
        if not isinstance(decoded, dict):
            out["errors"].append("%s segment is JSON but not an object" % label)
            continue
        out[label] = decoded

    if not out["header"]:
        # Not a JWT (or a header that never decoded). That is an ordinary answer for
        # this helper: report it in `errors` and hand back the empty document rather
        # than raising, so a caller can sweep a whole log file without try/except.
        if not out["errors"]:
            out["errors"].append("header segment is not a JSON object: not a JWT")
        return out

    alg = out["header"].get("alg")
    if isinstance(alg, str):
        out["alg"] = alg
        upper = alg.upper()
        out["weak_alg"] = upper == "NONE" or upper.startswith("HS")
    else:
        if alg is not None:
            out["errors"].append("header 'alg' is not a string")
        out["weak_alg"] = True
        out["errors"].append("header carries no usable 'alg'")

    typ = out["header"].get("typ")
    if isinstance(typ, str):
        out["typ"] = typ
    return out


# ------------------------------------------------------------------ RSA audit

def _severity_rank(severity):
    try:
        return _SEVERITY_ORDER.index(severity)
    except ValueError:
        return len(_SEVERITY_ORDER)


def _perfect_power(n):
    """Smallest exact power n = m^k (k >= 2) as (m, k), else None

    A cheap necessary condition first: if n is an exact k-th power then it is a
    k-th power modulo any small prime, so a modular filter rejects almost every
    exponent before the expensive integer root is attempted. Only the exponents
    that survive are handed to `algebra.iroot`, which keeps a 4096-bit modulus to
    a handful of Newton iterations.
    """
    if n < 4:
        return None
    for k in range(2, n.bit_length() + 1):
        if all(pow(n % p, (p - 1) // math.gcd(k, p - 1), p) in (0, 1)
               for p in (3, 5, 7, 11, 13)):
            root, exact = A.iroot(n, k)
            if exact and root > 1:
                return root, k
    return None


def _fermat_probe(n, budget):
    """Fermat factorisation bounded by `budget` rounds -> dict with the outcome

    Runs the whole budget and reports whether it succeeded, so "not close enough"
    and "gave up" can be told apart in the finding text. Only reached for odd,
    non-square, non-perfect-power n (Fermat on such input either returns p == 1 or
    terminates early, which is why the caller screens first).
    """
    if n % 2 == 0:
        return None
    a = math.isqrt(n)
    if a * a < n:
        a += 1
    for _ in range(budget):
        b2 = a * a - n
        b = A.perfect_square(b2)
        if b is not None:
            p, q = a - b, a + b
            if p > 1 and p * q == n:
                return p, q
        a += 1
    return None


def audit_rsa_key(n, e=None, extra_moduli=None, effort="normal"):
    """Audit one RSA modulus (optionally against a fleet) and report what is weak

    Why a tester needs it: "we found a 512-bit key on the VPN gateway" and "this
    appliance's keys share a prime with three other appliances" are report lines,
    and each of them is one of a handful of mechanical checks. This function runs
    them and hands back findings with a severity, so the same call works for a
    single certificate picked up during recon and for a batch of moduli from an
    inventory. It is honest about cost: `effort` selects how much work is spent on
    the search-based checks and any check that could not run says so in `checked`
    with the reason instead of quietly disappearing.

    Checks, in the order they are reported (finding id, severity in parentheses):
        modulus           n even, so 2 divides it (n_even, critical); n below
                          512/1024/2048 bits (n_bits_tiny critical /
                          n_bits_small high / n_bits_under_2048 medium)
        exponent          e == 1 leaks every plaintext (e_one, critical); e even is
                          not a valid public exponent (e_even, high); e < 3 is
                          invalid (e_invalid, high); e <= 17 means missing padding is
                          exploitable (small_exponent, info)
        perfect power     n == m^k (perfect_power, critical - trivially factorable)
        Fermat            p and q suspiciously close (fermat_close_primes, critical)
        Wiener            d below n^0.25/3, recoverable by continued fractions
                          (wiener, critical)
        smooth p-1        a factor p with p-1 smooth enough for Pollard p-1 in the
                          budget (p_minus_1_smooth, high)
        shared factor     n shares a prime with extra_moduli (shared_factor, critical)

    Args:
        n: the modulus (int, or bytes read big-endian).
        e: the public exponent when it is known (from the certificate/key). Not
            required - the exponent checks are then reported as not run.
        extra_moduli: other moduli from the same estate/fleet. A shared factor is
            the highest-value finding in this audit, so pass the whole inventory
            (or at least the siblings from the same appliance family) if you have
            it.
        effort: "quick" | "normal" | "deep". quick skips the p-1 search and uses a
            short Fermat budget; normal is the balanced default; deep spends far
            more time on Fermat and p-1. In BOTH non-quick tiers the failures are
            reported as bounded ("nothing within N iterations"), never as a claim
            that the key is safe.

    Returns:
        {
          "n_bits": int,
          "e": int or None,
          "findings": [{"id", "severity", "detail"}, ...] worst finding first,
          "checked": [{"check", "ok", "detail"}, ...] - one entry per check, `ok`
                     False meaning "could not run", with the reason in `detail`.
        }
    """
    if isinstance(n, (bytes, bytearray)):
        n = R.bytes_to_long(n)
    try:
        n = int(n)
    except (TypeError, ValueError):
        raise ValueError("audit_rsa_key: n must be an integer or bytes")
    if n <= 1:
        raise ValueError("audit_rsa_key: n must be > 1")
    if e is not None:
        try:
            e = int(e)
        except (TypeError, ValueError):
            raise ValueError("audit_rsa_key: e must be an integer")
    if effort not in ("quick", "normal", "deep"):
        raise ValueError("effort must be 'quick', 'normal' or 'deep'")

    if effort == "quick":
        pm1_bound, fermat_budget, deep = 0, 100000, False
    elif effort == "deep":
        pm1_bound, fermat_budget, deep = 50000, 1000000, True
    else:
        pm1_bound, fermat_budget, deep = 20000, 300000, False

    n_bits = n.bit_length()
    findings = []
    checked = []

    def note(check, ok, detail):
        checked.append({"check": check, "ok": bool(ok), "detail": detail})

    def find(fid, severity, detail):
        findings.append({"id": fid, "severity": severity, "detail": detail})

    note("modulus", True, "n is %d bits" % n_bits)
    if n_bits < 2048:
        # The ids carry the word "bits" so a report reader (or a grep over a JSON
        # finding list) can group every size problem together, whatever the threshold.
        # Only a sub-256-bit modulus is called critical: at that size factoring is a
        # coffee break, whereas 512/1024-bit keys are weak (high) rather than already
        # broken, and a report that cries critical at 511 bits would drown the real
        # "this key shares a prime with the router next door" finding next to it.
        if n_bits < 256:
            find("n_bits_tiny", "critical",
                 "n is only %d bits: factorable in a coffee break, not a usable key, "
                 "so treat the key material as public" % n_bits)
        elif n_bits < 512:
            find("n_bits_very_small", "high",
                 "n is %d bits: below 512 bits, which is factorable with modest "
                 "public tooling and should be rotated immediately" % n_bits)
        elif n_bits < 1024:
            find("n_bits_small", "high",
                 "n is %d bits: below every modern guideline (NIST SP 800-57), "
                 "reachable by modest hardware" % n_bits)
        else:
            find("n_bits_under_2048", "medium",
                 "n is %d bits: accepted by legacy TLS stacks but below the current "
                 "2048-bit floor" % n_bits)

    if e is None:
        note("exponent", False, "no e supplied: every exponent check was skipped")
    else:
        note("exponent", True, "e = %d" % e)
        if e == 1:
            find("e_one", "critical",
                 "e == 1: encryption is the identity, every ciphertext is the plaintext")
        elif e % 2 == 0:
            find("e_even", "high",
                 "e == %d is even: the map is not a bijection mod n, so decryption "
                 "is ill-defined and no standard implementation will accept it" % e)
        elif e < 3:
            find("e_invalid", "high", "e == %d is not a valid public exponent" % e)
        elif e <= 17:
            find("small_exponent", "info",
                 "e == %d is small: harmless with a correct padding scheme, but any "
                 "unpadded or partially padded use becomes a small-exponent attack "
                 "(integer root / Hasad broadcast)" % e)

    if n % 2 == 0:
        find("n_even", "critical",
             "n is even: 2 divides n, so the modulus is factored already")
        note("perfect_power", False, "skipped: n is even, the factor is known")
        note("fermat", False, "skipped: n is even, the factor is known")
        note("wiener", False, "skipped: n is even, the factor is known")
        note("p_minus_1", False, "skipped: n is even, the factor is known")
    else:
        power = _perfect_power(n)
        if power is None:
            note("perfect_power", True, "n is not an exact power m^k (k >= 2)")
        else:
            base, expo = power
            factor = pow(base, expo - 1)
            if 1 < factor < n:
                find("perfect_power", "critical",
                     "n = m^%d with m = %d: factors are p = m and q = m^%d"
                     % (expo, base, expo - 1))
            else:
                find("perfect_power", "info",
                     "n is an exact %d-th power of m = %d (m does not split into "
                     "two factors of the expected size)" % (expo, base))

        close = _fermat_probe(n, fermat_budget)
        if close:
            p, q = close
            # Report sizes, not the factors themselves: a report line has to stay
            # readable, and |p - q| is what makes Fermat cheap (it costs about
            # |p - q|^2 / (4*sqrt(n)) rounds).
            find("fermat_close_primes", "critical",
                 "p and q are %d-bit primes only %d bits apart (|p-q| has %d bits): "
                 "Fermat factorisation recovers them in %d rounds, which is a "
                 "mis-generated key rather than a size problem"
                 % (min(p, q).bit_length(), abs(p - q).bit_length(),
                    abs(p - q).bit_length(), (abs(p - q) ** 2) // (4 * A.isqrt(n)) + 1))
            note("fermat", True, "p and q are close enough for Fermat")
        else:
            note("fermat", True,
                 "no factorisation within %d Fermat iterations (bounded search, not "
                 "a proof that p and q are far apart)" % fermat_budget)

        if e is None or e <= 1:
            note("wiener", False,
                 "no usable e supplied, so the continued-fraction convergents of e/n "
                 "cannot be computed")
        else:
            hit = A.wiener_recover_d(e, n)
            if hit is None:
                note("wiener", True, "d does not meet the Wiener bound (d < n^0.25/3)")
            else:
                d, p, q = hit
                find("wiener", "critical",
                     "Wiener attack recovered d = %d (%d bits) with p = %d, q = %d"
                     % (d, d.bit_length(), p, q))
                note("wiener", True, "small d recovered from the convergents of e/n")

        if pm1_bound <= 0:
            note("p_minus_1", False,
                 "effort=quick skips the Pollard p-1 search; rerun with "
                 "effort='normal' or 'deep' to test p-1 smoothness")
        else:
            factor = M.pollard_pm1(n, bound=pm1_bound)
            if factor is None:
                note("p_minus_1", True,
                     "no factor p with p-1 smooth up to %d (bounded search)" % pm1_bound)
            else:
                find("p_minus_1_smooth", "high",
                     "Pollard p-1 found the factor %d: its p-1 is smooth up to %d"
                     % (factor, pm1_bound))
                note("p_minus_1", True, "p-1 smoothness confirmed, p = %d" % factor)

    if extra_moduli is None:
        note("shared_factor", False, "no extra_moduli supplied: nothing to compare with")
    else:
        others = []
        skip = 0
        for value in extra_moduli:
            if isinstance(value, (bytes, bytearray)):
                value = R.bytes_to_long(value)
            try:
                value = int(value)
            except (TypeError, ValueError):
                skip += 1
                continue
            if value > 1:
                others.append(value)
        if not others:
            note("shared_factor", False,
                 "extra_moduli carried no usable modulus (%d unparsable)" % skip)
        else:
            res = batch_gcd([n] + others, progress=None)
            hits = res["pairs"]
            if not hits:
                note("shared_factor", True,
                     "no shared prime with %d other modulus/moduli" % len(others))
            else:
                factors = sorted({p["factor"] for p in hits})
                find("shared_factor", "critical",
                     "shares a prime factor (%s) with %d other modulus/moduli: both "
                     "private keys are recoverable by gcd alone, which points at a "
                     "weak or forked RNG rather than at the key sizes"
                     % (", ".join(str(f) for f in factors[:4]), len(hits)))
                note("shared_factor", True,
                     "%d modulus/moduli share a factor with n" % len(hits))

    findings.sort(key=lambda f: _severity_rank(f["severity"]))
    return {"n_bits": n_bits, "e": e, "findings": findings, "checked": checked}


# ------------------------------------------------------------------ PRNG fingerprint

def _lcg_replay(params, outputs):
    """True when x_{i+1} = a*x_i + c (mod m) reproduces the whole observation"""
    a, c, m = params["a"], params["c"], params["m"]
    if m <= 1:
        return False
    state = int(outputs[0]) % m
    for observed in outputs[1:]:
        state = (a * state + c) % m
        if state != int(observed) % m:
            return False
    return True


def _glibc_words_ok(rec, outputs):
    """Check a recovered TYPE_3 window against the observations it claims to explain

    The lower layer returns `words`, one 32-bit state word per observation, with
    `rand()` having printed `word >> 1`. Two things are therefore checkable without
    any held-out data: every word reproduces its observation, and the window follows
    the generator's own recurrence `w_j = w_{j-31} + w_{j-3} (mod 2^32)`. That is a
    consistency proof, not a prediction proof, which is why `_glibc_attempt` prefers a
    held-out tail whenever one is available and only falls back to this check.
    """
    words = [int(w) & _MASK32 for w in rec.get("words", [])]
    if len(words) < len(outputs):
        return False
    for pos, observed in enumerate(outputs):
        if (words[pos] >> 1) != (int(observed) & 0x7fffffff):
            return False
    for pos in range(31, len(outputs)):
        if words[pos] != (words[pos - 31] + words[pos - 3]) & _MASK32:
            return False
    return True


def _glibc_attempt(outputs):
    """Recover the glibc TYPE_3 state -> a hit dict, or None when it cannot be pinned

    Recovery only counts when it can be *checked forwards*. That is why a tail of the
    observation is held out whenever there is one: the state is recovered from the
    prefix and its prediction must then reproduce the values it never saw, exactly as
    with MT19937. Only when there is no tail to hold out (the caller supplied barely
    enough outputs) does a self-consistency check stand in, and that hit is reported
    with "medium" confidence rather than sold as verified.

    A prefix whose state fits but whose prediction diverges on the tail is discarded
    instead of being returned, because that is precisely the shape of the silent wrong
    answer this module exists to avoid.
    """
    n = len(outputs)
    prefixes = []
    if n > 40:
        for hold in (min(32, n - 40), n - 40, 8, 4):
            if 35 <= n - hold < n:
                prefixes.append(n - hold)
    prefixes.append(n)
    seen = set()
    for prefix in prefixes:
        if prefix in seen:
            continue
        seen.add(prefix)
        try:
            rec = PE.glibc_rand_recover(outputs[:prefix])
        except Exception:                              # pragma: no cover - defensive
            continue
        if rec is None:
            continue
        if prefix < n:
            predicted = PE.glibc_rand_predict(outputs[:prefix], n - prefix)
            tail = [int(o) & 0x7fffffff for o in outputs[prefix:]]
            if predicted == tail:
                return {
                    "family": "glibc_rand",
                    "confidence": "high",
                    "state": {"state": rec["state"], "index": rec["index"]},
                    "predict": PE.glibc_rand_predict(outputs, 4),
                    "detail": ("TYPE_3 additive generator recovered from the first %d "
                               "outputs and verified against the %d held-out values "
                               "that follow (they match exactly); %d state candidates "
                               "were consistent"
                               % (prefix, n - prefix,
                                  rec.get("solutions_considered", 0))),
                }
            continue
        if _glibc_words_ok(rec, outputs):
            return {
                "family": "glibc_rand",
                "confidence": "medium",
                "state": {"state": rec["state"], "index": rec["index"]},
                "predict": PE.glibc_rand_predict(outputs, 4),
                "detail": ("TYPE_3 additive generator fitted to all %d outputs and "
                           "internally consistent (every word reproduces its output "
                           "and the recurrence holds); no held-out value was available "
                           "to confirm the prediction, so capture more to upgrade this "
                           "to high confidence" % n),
            }
    return None


def _xorshift_replay(state, outputs):
    """`state` is the value that produced outputs[0]; state == output for xorshift32"""
    value = int(state) & _MASK32
    for observed in outputs:
        if value != (int(observed) & _MASK32):
            return False
        value = PE.xorshift32_next(value)
    return True


def _java_replay(seed, outputs):
    """`seed` is the internal 48-bit state; replay `next(32)` against the observations"""
    state = int(seed) & _MASK48
    for observed in outputs:
        state = (state * _JAVA_MAGIC + _JAVA_ADDEND) & _MASK48
        value = state >> 16
        if value >= 0x80000000:
            value -= 0x100000000
        if value != int(observed):
            return False
    return True


def _prng_candidates(outputs, deep, tried, only=None):
    """Run each family's recovery in cost order, appending to `tried`; return the hits

    Cost order is deliberate: glibc (one propagation, no search), then xorshift32 (a
    closed-form inversion), then Java Random (a 2^16 sweep), then a generic LCG
    (arithmetic on the difference sequence), and finally MT19937 (624 untemper steps,
    which only makes sense once the cheap explanations are gone). `only` restricts the
    run to a single family name - that is how the screening loop in `detect_weak_prng`
    stops paying for the expensive families as soon as a cheap one explains the data.

    Every hit is checked forwards before it is returned, through the family's own
    verification helper: glibc and MT19937 hold out a tail of the observation and
    require the recovered state to predict it, xorshift32/Java/LCG re-derive every
    supplied value from the recovered parameters. The lower layers verify internally
    too, but repeating it here means one rule governs all five families, so a change
    in a lower layer cannot turn a failed recovery into a confident claim.
    """
    hits = []
    n = len(outputs)

    def want(family):
        return only is None or only == family

    if want("glibc_rand"):
        if n >= 35 and all(0 <= v < (1 << 31) for v in outputs):
            hit = _glibc_attempt(outputs)
            if hit is None:
                tried.append({"family": "glibc_rand", "ok": False,
                              "note": ("no single state is determined by these %d "
                                       "outputs (the bit rand() discards stays "
                                       "ambiguous); capture more - about 100 were "
                                       "needed in testing" % n)})
            else:
                hits.append(hit)
                tried.append({"family": "glibc_rand", "ok": True,
                              "note": hit["detail"]})
        elif n >= 35:
            tried.append({"family": "glibc_rand", "ok": False,
                          "note": "outputs reach 2^31 or beyond, which rand() (31 "
                                  "bits) cannot produce"})
        else:
            tried.append({"family": "glibc_rand", "ok": False,
                          "note": "needs >= 35 outputs to pin the 31-word state down "
                                  "(have %d)" % n})
        if hits and not deep:
            return hits

    if want("xorshift32"):
        if all(0 <= v <= _MASK32 for v in outputs):
            try:
                rec = PE.xorshift_recover(outputs)
            except Exception as exc:                   # pragma: no cover - defensive
                rec, why = None, "raised %s" % exc
            else:
                why = "no non-zero state reproduces the whole observation"
            if rec and _xorshift_replay(rec["state"], outputs):
                hits.append({
                    "family": "xorshift32",
                    "confidence": "high",
                    "state": {"state": rec["state"]},
                    "predict": PE.xorshift_predict(outputs, 4),
                    "detail": ("xorshift32 (13,17,5) state inverted out of outputs[1] "
                               "and replayed over %d observed values" % n),
                })
                tried.append({"family": "xorshift32", "ok": True,
                              "note": "state recovered and replayed"})
            else:
                tried.append({"family": "xorshift32", "ok": False, "note": why})
        else:
            tried.append({"family": "xorshift32", "ok": False,
                          "note": "outputs exceed 32 bits, which xorshift32 cannot "
                                  "produce"})
        if hits and not deep:
            return hits

    if want("java_random"):
        if all(-(1 << 31) <= v < (1 << 31) for v in outputs) and n >= 3:
            try:
                rec = PE.java_random_recover(outputs)
            except Exception as exc:                   # pragma: no cover - defensive
                rec, why = None, "raised %s" % exc
            else:
                why = "no 48-bit state in range reproduces the whole observation"
            if rec and _java_replay(rec["seed"], outputs):
                hits.append({
                    "family": "java_random",
                    "confidence": "high",
                    "state": {"seed": rec["seed"]},
                    "predict": PE.java_random_predict(outputs, 4),
                    "detail": ("java.util.Random (48-bit LCG, nextInt) internal state "
                               "recovered from the printed high bits and replayed over "
                               "%d observed values" % n),
                })
                tried.append({"family": "java_random", "ok": True,
                              "note": "internal state recovered and replayed"})
            else:
                tried.append({"family": "java_random", "ok": False, "note": why})
        else:
            tried.append({"family": "java_random", "ok": False,
                          "note": "needs signed 32-bit `nextInt()` values"})
        if hits and not deep:
            return hits

    if want("lcg"):
        if n >= 4:
            try:
                rec = A.lcg_recover(outputs)
            except Exception as exc:                   # pragma: no cover - defensive
                rec, why = None, "raised %s" % exc
            else:
                why = "no (a, c, m) reproduces the whole observation"
            if rec and _lcg_replay(rec, outputs):
                nxt = int(outputs[-1])
                pred = []
                for _ in range(4):
                    nxt = (rec["a"] * nxt + rec["c"]) % rec["m"]
                    pred.append(nxt)
                hits.append({
                    "family": "lcg",
                    "confidence": "high",
                    "state": {"a": rec["a"], "c": rec["c"], "m": rec["m"]},
                    "predict": pred,
                    "detail": ("linear congruential generator replayed over %d observed "
                               "values: x_next = (a*x + c) mod m with a = %d, c = %d, "
                               "m = %d" % (n, rec["a"], rec["c"], rec["m"])),
                })
                tried.append({"family": "lcg", "ok": True,
                              "note": "parameters recovered and replayed"})
            else:
                tried.append({"family": "lcg", "ok": False, "note": why})
        else:
            tried.append({"family": "lcg", "ok": False,
                          "note": "needs >= 4 consecutive outputs to fit a, c, m"})
        if hits and not deep:
            return hits

    if want("mt19937"):
        if n >= _MT_MIN_WORDS and all(0 <= v <= _MASK32 for v in outputs):
            # `clone_from_outputs` untempers the 624 words and leaves the clone
            # standing *right after them* (index == N), so its next call twists the
            # recovered block and yields observation 625 onwards. Two consequences,
            # both of which an earlier version got wrong: the held-out tail of the
            # observation is the evidence (replaying the 624 input words through the
            # clone rejected every genuine MT19937 stream), and the clone must then be
            # advanced through the rest of the observation before `predict` - otherwise
            # the reported "next 4" are four values the caller already gave us.
            try:
                probe = PR.clone_from_outputs(outputs[:_MT_MIN_WORDS])
            except Exception as exc:                   # pragma: no cover - defensive
                probe, why = None, "raised %s" % exc
            else:
                why = "the cloned state does not replay the held-out observations"
            if probe is not None:
                tail_ok = True
                for observed in outputs[_MT_MIN_WORDS:]:
                    if probe.next32() != (int(observed) & _MASK32):
                        tail_ok = False
                        break
                verified = n > _MT_MIN_WORDS
                if tail_ok:
                    live = PR.clone_from_outputs(outputs[:_MT_MIN_WORDS])
                    for _ in range(n - _MT_MIN_WORDS):
                        live.next32()
                    pred = [live.next32() for _ in range(4)]
                    if verified:
                        detail = ("MT19937 state untempered from the first %d words and "
                                  "verified against the %d held-out values that follow "
                                  "(they match exactly); `state.clone` is a PR.MT19937 "
                                  "standing after the observation and predicts the whole "
                                  "future stream" % (_MT_MIN_WORDS, n - _MT_MIN_WORDS))
                        confidence = "high"
                    else:
                        detail = ("MT19937 state untempered from exactly %d words: the "
                                  "clone reproduces the stream by construction, but no "
                                  "held-out value could confirm it, so this is self-"
                                  "consistent rather than verified - capture one more "
                                  "word to make it a high-confidence claim"
                                  % _MT_MIN_WORDS)
                        confidence = "medium"
                    hits.append({
                        "family": "mt19937",
                        "confidence": confidence,
                        "state": {"clone": live},
                        "predict": pred,
                        "detail": detail,
                    })
                    tried.append({"family": "mt19937", "ok": True,
                                  "note": detail})
                else:
                    tried.append({"family": "mt19937", "ok": False, "note": why})
        elif n >= _MT_MIN_WORDS:
            tried.append({"family": "mt19937", "ok": False,
                          "note": "outputs exceed 32 bits, which getrandbits(32) cannot "
                                  "produce"})
        else:
            tried.append({"family": "mt19937", "ok": False,
                          "note": "needs >= %d 32-bit words, only %d observed"
                                  % (_MT_MIN_WORDS, n)})

    return hits

def detect_weak_prng(outputs, effort="normal"):
    """Fingerprint the generator behind an observed "random" output sequence

    Why a tester needs it: session tokens, password-reset nonces, API keys,
    invitation codes and "unpredictable" object IDs are the highest-value material
    an engagement collects, and their security rests entirely on the generator. A
    sequence of a few dozen observed values is often enough to name the generator
    and then predict every future value - "the tokens look random" becomes "the
    tokens are an LCG, here are the next four" without touching the target again.
    This function runs the recoveries in escalating cost order and claims a family
    only when that family's recovery *replays every observed value*; a sequence it
    cannot reproduce gets family=None, because a wrong family name in a report is
    worse than "unidentified".

    Order and what each family is:
        glibc rand()  additive lagged Fibonacci (TYPE_3), >= 35 values
        xorshift32    Marsaglia (13,17,5), state == output
        java.util.Random  48-bit LCG whose high 32 bits are printed
        generic LCG   x_next = (a*x + c) mod m, modulus estimated when unknown
        MT19937       >= 624 32-bit words, state untempered from the observations

    Args:
        outputs: the observed integers, oldest first. Bytes/str entries are
            converted to ints (big-endian / digit string). Negative values are kept
            (Java `nextInt()` prints them).
        effort: "quick" | "normal" | "deep" ("fast" is accepted as a synonym of
            "quick"). After the first verified family wins, quick and normal stop;
            deep keeps going so that the `tried` list covers every family - useful
            when the goal is to rule generators out as well as in.

    Returns:
        {
          "family": str or None ("glibc_rand", "xorshift32", "java_random", "lcg",
                    "mt19937"),
          "confidence": "high" | "medium" | "low" | None. "high" means the recovery
                    was checked *forwards*: state recovered from part of the
                    observation, prediction matched the values it never saw. "medium"
                    means the state reproduces everything supplied but there was no
                    held-out value to confirm it (exactly 624 MT19937 words, or barely
                    enough glibc outputs), "low" is reserved for a structurally
                    possible but unverified fit, and None accompanies family None.
          "state": the recovered state (dict; for MT19937 it holds the PR.MT19937
                    clone itself),
          "predict": [next 4 values] or None,
          "detail": str - what was verified, or why nothing was claimed,
          "weak_prng": bool - the convenience verdict for a report line,
          "tried": [{"family", "ok", "note"}, ...] - every attempt, including the
                    ones that could not run because there were too few outputs.
        }
    """
    if isinstance(outputs, (bytes, bytearray, str)):
        raise ValueError("outputs must be a sequence of ints, not a single blob")
    values = []
    for item in outputs:
        if isinstance(item, (bytes, bytearray)):
            values.append(R.bytes_to_long(item))
        else:
            values.append(int(item))

    tier = {"fast": "quick", "quick": "quick", "normal": "normal", "deep": "deep"}
    if effort not in tier:
        raise ValueError("effort must be 'quick', 'normal' or 'deep'")
    deep = tier[effort] == "deep"

    result = {"family": None, "confidence": None, "state": None, "predict": None,
              "detail": "", "weak_prng": False, "tried": []}
    if not values:
        result["detail"] = "no outputs given: nothing to fingerprint"
        return result
    if len(values) < 3:
        result["detail"] = ("only %d output(s): every recovery here needs at least 3, "
                            "so no family was tested to a conclusion" % len(values))
        return result

    if not deep:
        # Screening order is a cost order (see `_prng_candidates`): cheap,
        # structurally narrow families first. A verified hit short-circuits, so the
        # common case pays for one or two recoveries rather than all five.
        tried = []
        hits = []
        for family in ("glibc_rand", "xorshift32", "java_random", "lcg", "mt19937"):
            hits = _prng_candidates(values, deep=False, tried=tried, only=family)
            if hits:
                break
    else:
        tried = []
        hits = _prng_candidates(values, deep=True, tried=tried)

    result["tried"] = tried
    if not hits:
        result["detail"] = ("no tested family reproduces the observed sequence "
                            "(%d value(s)); see `tried` for what was ruled out"
                            % len(values))
        return result

    best = hits[0]
    result["family"] = best["family"]
    result["confidence"] = best["confidence"]
    result["state"] = best["state"]
    result["predict"] = best["predict"]
    result["detail"] = best["detail"]
    result["weak_prng"] = best["confidence"] == "high"
    if len(hits) > 1:
        result["detail"] += ("; %d family/families reproduce this data, the "
                             "highest-priority one is reported"
                             % len(hits))
        result["ambiguous"] = [h["family"] for h in hits]
    return result
